"""Validated request models shared by Turn and Agent Thread routes."""

from __future__ import annotations

from pydantic import BaseModel, ConfigDict, Field, model_validator

from backend.domain.execution_config import RuntimeModelPatch, TurnConfigPatch, TurnExecutionConfig


class QueuedDeliveryRequest(BaseModel):
    model_config = ConfigDict(extra="forbid")

    message_ids: list[str] = Field(min_length=1, max_length=100)


class SteerTurnRequest(BaseModel):
    model_config = ConfigDict(extra="forbid")

    delivery_id: str = Field(min_length=1, max_length=200)
    message_ids: list[str] = Field(min_length=1, max_length=100)


class CreateTurnRequest(TurnExecutionConfig):
    model_config = ConfigDict(extra="forbid")

    session_id: str = Field(min_length=1, max_length=200)
    thread_id: str = Field(min_length=1, max_length=200)
    parent_id: str = Field(default="", max_length=200)
    message: dict[str, object] | None = None
    queued_delivery: QueuedDeliveryRequest | None = None

    @model_validator(mode="after")
    def validate_message_source(self):
        if (self.message is None) == (self.queued_delivery is None):
            raise ValueError("message and queued_delivery are mutually exclusive")
        return self


class RewindTurnRequest(TurnExecutionConfig):
    message: dict[str, object]
    delivery_id: str | None = Field(default=None, min_length=1, max_length=200)


class CurrentDataRequest(BaseModel):
    session_id: str = Field(min_length=1, max_length=128, pattern=r"^[A-Za-z0-9][A-Za-z0-9_-]*$")
    current_data_idx: int = Field(ge=0)


class ForkTurnRequest(BaseModel):
    thread_id: str | None = Field(default=None, min_length=1, max_length=200)

    @model_validator(mode="before")
    @classmethod
    def reject_client_turn_id(cls, value):
        if isinstance(value, dict) and "id" in value:
            raise ValueError("Fork Turn ID is generated by the backend.")
        return value


__all__ = [
    "CreateTurnRequest",
    "CurrentDataRequest",
    "ForkTurnRequest",
    "QueuedDeliveryRequest",
    "RewindTurnRequest",
    "RuntimeModelPatch",
    "SteerTurnRequest",
    "TurnConfigPatch",
    "TurnExecutionConfig",
]
